spring:
  datasource:
    url: jdbc:h2:mem:examdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration