spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_exam_db
    username: postgres
    password: 4844
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  flyway:
#    enabled: true
#    locations: classpath:db/migration

#spring:
#  datasource:
#    url: jdbc:h2:mem:examdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect